### ISSUE TITLE
Comments hierarchy messed up

### ISSUE THREAD

**Issue by oh1apps** [laurencedawson/sync-for-lemmy#241]
**Describe the bug**  
Comments hierarchy is messed up - sometimes parent aren't showing, or showing in wrong place as orphaned items.

**Steps to Reproduce**  
1. Go to comments section

**Expected behavior**
Comments showing in right order. respecting hierarchy 

**Screenshots**
For comparison there's screenshot from Liftoff

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6a]
 - Android: [e.g. 13]
 - Sync version: [latest beta

![Screenshot_20230804-164101](https://github.com/laurencedawson/sync-for-lemmy/assets/10464487/3c3bcc2b-7a5f-4a41-b6f7-70d945cf1b93)
![Screenshot_20230804-164115](https://github.com/laurencedawson/sync-for-lemmy/assets/10464487/056ad487-5cde-47af-a794-a1e6ebe485fa)
![Screenshot_20230804-164120](https://github.com/laurencedawson/sync-for-lemmy/assets/10464487/ca10365e-ad63-4b49-ac4d-b3e0a38f8617)
]

**Comment by RobinFlikkema** [comment]
Same here; however I only found it when one of the comments in the tree was disabled.

![Screenshot_20230804_214100_Sync~2](https://github.com/laurencedawson/sync-for-lemmy/assets/4777401/67e22880-9cef-4a8b-a68f-cbb9da28218c)
From: https://lemmy.world/post/2580455


**Device information**

    Sync version: v23.08.03-16:15    
    Sync flavor: googlePlay    
    
    Ultra user: false    
    View type: Slides    
    Push enabled: false    
    
    Device: b0s    
    Model: samsung SM-S908B    
    Android: 13

**Comment by WegnerDan** [comment]
Probably the same as this:

https://github.com/laurencedawson/sync-for-lemmy/issues/133

**Comment by laurencedawson** [comment]
I think I've fixed this. Leaving it open until beta 29 goes live for everyone.

**Comment by tiritibambix** [comment]
Hello. I've installed beta 29 and still experience this bug.

**Comment by WegnerDan** [comment]
Same here, sorting by Top is still messed up

**Comment by pwd-github** [comment]
What version of Lemmy is your home instance and the remote instance on?

**Comment by WegnerDan** [comment]
I had this issue on lemmy.world BE: 0.18.4

**Comment by laurencedawson** [comment]
Screenshot?

**Comment by WegnerDan** [comment]
Post: https://lemmy.world/post/3100679
Comment: https://lemmy.world/comment/2350556

The comment has no "child comments" on the browser version of lemmy. 

<details>
<summary>Screenshots</summary>



![Screenshot_20230814-101634](https://github.com/laurencedawson/sync-for-lemmy/assets/6908247/1694701e-47d8-4a45-8950-c59de1d4e733)

after clicking on "View more(2)", it looks the same, but the "View more" disappears

![Screenshot_20230814-101641](https://github.com/laurencedawson/sync-for-lemmy/assets/6908247/92cbd758-3f79-469a-86d5-4c97436f8753)



</details>

**Comment by tiritibambix** [comment]
Same here from lemmy.ml to lemmy.world

![Screenshot_2023-08-13-18-52-34-66_f8c215a6f14c21709a2994385a7dc495](https://github.com/laurencedawson/sync-for-lemmy/assets/69852851/03958a49-e523-48f7-b4a4-b89844a624fd)

In this screenshot, ops comment should be under cory_lorwy's comment.
Clicking on "view more" makes it desapear and nothing more happens.

**Comment by tiritibambix** [comment]
Another screenshot. I don't really know how to read that 😅
![Uploading Screenshot_2023-08-17-12-36-04-67_f8c215a6f14c21709a2994385a7dc495.jpg…]()

**Comment by laurencedawson** [comment]
Fixed for the next release.
